### ISSUE TITLE
Include Decimal Points

### ISSUE THREAD

**Issue by Safnaj** [der-Lehmann/number-flip-animation#1]
When we have decimal pointd as 231.99 the points is now showing.

**Comment by der-Lehmann** [comment]
Yes, as mentioned in the [readme](https://github.com/der-Lehmann/number-flip-animation/tree/master#Limitations) that is currently not possible.  
However I took your issue as a reason to implement such a feature.  
I just created a new [branch for version 2](https://github.com/der-Lehmann/number-flip-animation/tree/version-2.0) of this package.  

With the current state of the code on that branch it is already possible to display numbers with a decimal place.

**Comment by der-Lehmann** [comment]
I just published Version two of this package, so that numbers can now be displayed with a decimal point.

**Comment by Safnaj** [comment]
Awesome @der-Lehmann
