### ISSUE TITLE
All options are required for class NumberFlip (typescript)

### ISSUE THREAD

**Issue by milosztisagroup** [der-Lehmann/number-flip-animation#2]
### Currently
Typescript require all options to provide for

```
const numberFlip = new NumberFlip({
  rootElement: document.getElementById('number-flip'),
});
```

![Zrzut ekranu 2024-09-18 o 09 59 26](https://github.com/user-attachments/assets/8b323103-c7b5-4724-a373-b632a0dc3e40)

### Expected:
Only `rootElement` is required

### Hint
Before version 2.0 types included `?`
```
durationFlip?: number;
```

**Comment by der-Lehmann** [comment]
You are right.
The optional parameters are not defined as such in the type hint, which leads to typescript complaining when they are not provided.

I just fixed the issue with the commit https://github.com/der-Lehmann/number-flip-animation/commit/a03ce5c84abfd6c72a8d80d5b146ab06cc86932b.
Also a new Version (2.0.1) is published on npm.
